### ISSUE TITLE
Fold null checked method calls into safe navigation operators

### ISSUE THREAD

**Issue by nathanmbrown** [cheptsov/AdvancedExpressionFolding#10]
e.g.
```
if (foo != null)
  foo.bar();
```
becomes
`foo?.bar();`

Boolean null checked expressions could have special handling, e.g.
`return foo != null && foo.bar()`
becomes
`return foo?.bar()`
  
You could also fold assignments:
  `baz = foo != null ? foo.bar() : null;`
into
  `baz = foo?.bar()?;`

This would only apply when the fallback was explicitly null though...

**Comment by nathanmbrown** [comment]
You could also fold:
  `baz = foo != null ? foo.bar() : null;`
into
  `baz = foo?.bar();`

**Comment by stokito** [comment]
Also it would be great to replase this ugly `Optional` shit:
```java
opt.ifPresent(this::print);
```
to
```groovy
opt?.print;
```

**Comment by cheptsov** [comment]
https://twitter.com/andrey_cheptsov/status/834803349757231107
