### ISSUE TITLE
Folding hides errors

### ISSUE THREAD

**Issue by sabi0** [cheptsov/AdvancedExpressionFolding#107]
![image](https://user-images.githubusercontent.com/11509875/35446968-aae2b790-02b6-11e8-909a-a27564cdc29c.png)

**Comment by ciscorucinski** [comment]
I was thinking that this was something outside of IntelliJ IDEA's ability (and it is); however, if the `identifier` has issues (as the above issue), then the folding should not occur. 

I think this is a good way to fix this??

**Comment by jfcabral** [comment]
Hi, I believe this behaviour was already reported here: https://github.com/cheptsov/AdvancedExpressionFolding/issues/22

As @ciscorucinski mentioned, it seems to be a limitation of IntelliJ IDEA. See https://youtrack.jetbrains.com/issue/IDEA-61533 and let's vote in it!

**Comment by sabi0** [comment]
Fixed as of 181.3494.3
https://blog.jetbrains.com/idea/2018/02/intellij-idea-2018-1-eap-editor-enhancements-and-more/
