### ISSUE TITLE
Folding `.stream()` to nothing, looks weird with call-chain-invocation-per-line formatting

### ISSUE THREAD

**Issue by ewirch** [cheptsov/AdvancedExpressionFolding#113]
This
```
return Seasons.all()
    .stream()
    .filter(season -> season.getDate().isAfter(today))
```

get's folded to

```
return Seasons.all()

    .filter(season -> season.getDate().isAfter(today))
```
if "... Stream expressions" is enabled, which is very irritating.

`.stream()` should be folded to something visible (or not at all, if placed alone on a line).

**Comment by stokito** [comment]
I tried and .stream() wasn't folded at all.
Maybe this is kind of a bug then please give us an example which we can compile.

**Comment by ewirch** [comment]
I do not use AdvancedExpressionFolding any more. You can close the issue, if you can't reproduce it.

**Comment by ciscorucinski** [comment]
@ewirch You should close this issue yourself. We cannot, and the developer is not active on here right now.
