### ISSUE TITLE
Do not fold multi-line string literals

### ISSUE THREAD

**Issue by sabi0** [cheptsov/AdvancedExpressionFolding#114]
I occasionally have a very long string in the code split onto several lines for better readability:
![image](https://user-images.githubusercontent.com/11509875/35981386-6c2ae7ca-0ced-11e8-8da1-8256789ca2e8.png)

Folding them back into a single very long line works against the plugin intention.

Probably the plugin should not fold the strings if there is no "interpolation", just a basic concatenation of the string literals.
Another option is to avoid folding strings beyond the configured right margin.

**Comment by ciscorucinski** [comment]
Duplicate of #29

**Comment by sabi0** [comment]
It is not a duplicate of #29. But a duplicate of #50.
Closed.
