### ISSUE TITLE
Groovy Truth

### ISSUE THREAD

**Issue by stokito** [cheptsov/AdvancedExpressionFolding#12]
I was a Groovy programmer for few years but now working on a lagacy Java 6 project and every night I'm crying into pillow.
Could you make a folding into [Groovy Truth](http://groovy-lang.org/semantics.html#Groovy-Truth) style?
I mean that instead of
```java
if (users.isEmpty()) {
// ...
}
```
fold it to simple
```groovy
if (users) {
// ...
}
```

**Comment by yburkouski** [comment]
I'm not an expert in programming languages but for me it looks very ambiguously. How will I tell that it's 'if (users.isEmpty())' or 'if (users == null)'? So I can foresee me every time unfolding it...

**Comment by ddimtirov** [comment]
As Advanced Folding advances, I can see the need of "Level of Detail" dropdown, allowing switching between settings which folds are enabled and which disabled (one day I'll create an issue to track it). 

Groovy-truth and other ambiguous folds would be useful then when one explores a codebase to get the gist and then switches to "lower level" view once they start working with the code.
