### ISSUE TITLE
IntelliJ 2018.2 (182.*) support

### ISSUE THREAD

**Issue by joserobjr** [cheptsov/AdvancedExpressionFolding#124]
IntelliJ is warning that Advanced Java Folding is incompatible with the latest version when we try to update IntelliJ from 2018.1 to 2018.2.

I noticed that the latest version of Advanced Java Folding is marked as compatible only with 181.* versions.

**Comment by jfcabral** [comment]
True story, I'm using 2018.2 and the latest version available for the plugin is v0.9.9.4

**Comment by ciscorucinski** [comment]
@joserobjr @cheptsov  you can close this now

https://github.com/cheptsov/AdvancedExpressionFolding/commit/1cc832c75777325bceb82095d8d53493875cde74
