### ISSUE TITLE
IntelliJ 2018.3 (183.*) Support

### ISSUE THREAD

**Issue by adnklauser** [cheptsov/AdvancedExpressionFolding#129]
The current release 0.9.9.8.2 is marked as only compatible with up to version 182.* of IntelliJ.

Staring at enterprise Java code all day is just not the same without Advanced Expression Folding 😊

**Comment by KOTRET** [comment]
installing 2018.3 downgrades the plugin to 0.9.9.4.
Please push a fix for that.

**Comment by ciscorucinski** [comment]
@adnklauser @KOTRET Until a fix is pushed, you can always manually download the plugin and install it in your IDE. That is a workaround for the restriction.

**Comment by KOTRET** [comment]
@ciscorucinski i've modified the plugin.xml in the jar 😁
