### ISSUE TITLE
three dots instead of every folding

### ISSUE THREAD

**Issue by mrBurny** [cheptsov/AdvancedExpressionFolding#136]
In editor every folding is replaced by three dots.
Idea version: 2019.3 EAP

<img width="329" alt="Screenshot 2019-10-28 at 22 42 23" src="https://user-images.githubusercontent.com/10338494/67723514-38a17880-f9d4-11e9-9c40-6c3203ab6b86.png">

**Comment by ciscorucinski** [comment]
This issue should be fixed via #135

**Comment by mrBurny** [comment]
@ciscorucinski fixed, thnx
