### ISSUE TITLE
Incompatible with IntelliJ 2020.2

### ISSUE THREAD

**Issue by Clashsoft** [cheptsov/AdvancedExpressionFolding#144]
The plugin (v0.9.9.8.5) does not work with IntelliJ 2020.2. In the Plugin settings, it says "Incompatible (until build 201.SNAPSHOT < IU-202.6397.94)".

![image](https://user-images.githubusercontent.com/4145923/89768770-5ae82b00-dafc-11ea-971d-c1398e114027.png)

**Comment by remal** [comment]
@cheptsov could you please fix it?

**Comment by bric3** [comment]
Just in case there's a small workaround that works with 2020.3 :

https://github.com/cheptsov/AdvancedExpressionFolding/issues/147#issuecomment-759356704

**Comment by Clashsoft** [comment]
Fixed in ebf95139fac20ef65038045f69ec19d028016a6f, no idea why it was not closed.
