### ISSUE TITLE
Not saved margins when moving to a new line methods

### ISSUE THREAD

**Issue by BorzdeG** [cheptsov/AdvancedExpressionFolding#20]
![](https://habrastorage.org/files/a21/923/9dd/a219239ddcb44e1d97267b3db00768e4.png)

**Comment by BorzdeG** [comment]
![](https://habrastorage.org/files/b3b/417/f1b/b3b417f1b07c4bda81f1ad1643f4574c.png)
![](https://habrastorage.org/files/ed7/85c/acc/ed785cacc0e84cefad6b30fa1997aa3c.png)

**Comment by cheptsov** [comment]
Have just fixed it in v0.4.9 (for both getters and setters)
