### ISSUE TITLE
setup folded to up

### ISSUE THREAD

**Issue by mibac138** [cheptsov/AdvancedExpressionFolding#24]
I believe instead of folding it it should be left as is.

**Comment by cheptsov** [comment]
@mibac138 Could you please provide more details?

**Comment by mibac138** [comment]
I used a TabLayout (from Android's support lib) and called `setupWithViewPager`. The method was later folded up to `upWithViewPager` which I believe is incorrect. In my opinion folding `set `(and possibly `get`) should only work when the next letter is capital (for ex. fold: `setAmount`, `setSomething` but do not fold things like: `setup`, `settle`)

**Comment by cheptsov** [comment]
@mibac138 Fixed in 0.6.0 (EAP)
