### ISSUE TITLE
StringBuilder folding results incorrect semantics

### ISSUE THREAD

**Issue by Quorte** [cheptsov/AdvancedExpressionFolding#28]
Code
```
String base = "test";
StringBuilder builder = new StringBuilder(base).append("test").append("test");
```
folds into the following:
```
var base = "test";
var builder = base += "test" + "test";
```
which may lead to assumption of changing `base` (because of `+=` operator)

(Version: 0.5.5)

**Comment by cheptsov** [comment]
Fixed  in https://plugins.jetbrains.com/plugin/9320-advanced-java-folding/update/33803 (Note, EAP channel). Please check when possible.
