### ISSUE TITLE
StringBuilder chain only folds first append

### ISSUE THREAD

**Issue by petteyg** [cheptsov/AdvancedExpressionFolding#3]
sb.append(var).append('\\').append(var2);
folds to

    sb += var.append('\\').append(var2);
I expected

    sb += var + '\\' + var2;
But

    sb.append("str").append(var);
folds as expected to

    sb += "str" + var;
so I expect it's something to do with the character literal.

**Comment by cheptsov** [comment]
Fixed in 0.2.2
