### ISSUE TITLE
Make plugin available to Android Studio

### ISSUE THREAD

**Issue by ciscorucinski** [cheptsov/AdvancedExpressionFolding#30]
Only supported IDE is IntelliJ IDEA. This should also work with Android Studio.

Edit: I downloaded the JAR and added it to Android Studio. Things seem to work well. But I cannot figure out how to enable / disable features as mentioned in the [Medium Post](https://medium.com/@andrey_cheptsov/making-java-code-easier-to-read-without-changing-it-adeebd5c36de).

**Comment by cheptsov** [comment]
Fixed in v0.7.0. Please give it a try.
