### ISSUE TITLE
Opening Android Studio throws a NoSuchMethodError

### ISSUE THREAD

**Issue by BehindTheMath** [cheptsov/AdvancedExpressionFolding#37]
I'm using Android Studio v2.3 with Adavnced Java Folding v0.7.4.

Every time I open Android Studio, I get a popup that AJF threw a NoSuchMethodError:

```
NoSuchMethodError: com.intellij.openapi.editor.ex.util.EditorUtil.getEditorEx(Lcom/intellij/openapi/fileEditor/FileEditor;)Lcom/intellij/openapi/editor/ex/EditorEx;
```

[Here](https://pastebin.com/TMaTVqAj) is the full stack trace.

**Comment by cheptsov** [comment]
Fixed with 0.7.5
