### ISSUE TITLE
Custom Folding options for this plugin are unavailable to Android Studio

### ISSUE THREAD

**Issue by ciscorucinski** [cheptsov/AdvancedExpressionFolding#44]
The ability to enable and disable custom folding via this plugin is not available in Android Studio at all.

Instead, everything appears to be selected in Android Studio without the ability to disable any folding options.

Android Studio
------
 ![android studio - code folding settings](https://cloud.githubusercontent.com/assets/8707125/24990772/3cac6b60-2051-11e7-898a-f6488935802e.png)

IntelliJ IDEA
-----

![intellij idea - code folding settings](https://cloud.githubusercontent.com/assets/8707125/24990777/447b0702-2051-11e7-939b-6202f972c304.png)

**Comment by cheptsov** [comment]
Should be fixed in 0.7.9 (EAP channel)
