### ISSUE TITLE
Add ability fold local variable type declarations into 'var' (like java 10 might have)

### ISSUE THREAD

**Issue by steveash** [cheptsov/AdvancedExpressionFolding#6]
Finally the [java language](http://openjdk.java.net/jeps/286) might get 'var' as a keyword on the left hand side of local variable declarations to avoid typing the nominal types when they can easily be inferred from the initialization expression: 
```java
var list = new ArrayList<String>();
```

As an optional feature of the AdvancedExpressionFolding plugin, perhaps intellij could go ahead and give us this readability improvement without having to wait 5 years for java 10.  Seems like a perfect fit to me :)  Understandably, many users might not want this by default so making it configurable like many other features of AEF is probably a good idea.

**Comment by cheptsov** [comment]
Sounds interesting. Can it replace https://github.com/cheptsov/AdvancedExpressionFolding/issues/5 ?

**Comment by steveash** [comment]
I think `var` is preferable over #5 but I still think both are reasonable features. Even in the example that you gave on 5 the +/- still looks better:
```java
var myMap = new HashMap<String,+Foo<+Bar>>();
```
But if i had to pick only one -- it would definitely be adding `var` :)

**Comment by cheptsov** [comment]
Implemented: https://twitter.com/andrey_cheptsov/status/818768206399700992

**Comment by steveash** [comment]
this is nice -- the only thing that i would consider is -- in the popup over the folded "var" token it displays the full text of the declaration including the initialization -- which is already displayed in the code so its just a much bigger popup than it needs to be.  Not really a problem but might be a little cleaner to just popup the folded code (the left hand side of the declaration)
