### ISSUE TITLE
`var` for non-final variables

### ISSUE THREAD

**Issue by anaumidis** [cheptsov/AdvancedExpressionFolding#60]
It would be nice if `Object o = new Object();`
folded to `var o = new Object();`
and only `final Object o = new Object();`
folded to `val o = new Object();`

**Comment by ciscorucinski** [comment]
You are talking about __non-final variables__  being folded into 'val' sometimes and 'var' the rest of the time; while __final variables__  are always folded into 'val'?

This is be design. If a __non-final variable__  was folded into 'val', then that means you can add the 'final' keyword to the __variable declaration__  and it will still compile everything the same.

**Comment by anaumidis** [comment]
Sorry, my comment was misleading.

What I'm seeing is that at this moment both are folded to `val`.
And I think the ideal would be to fold the non-final variables to `var`.

**Comment by ciscorucinski** [comment]
Try to reassign one of the `val` variables

    int i = 20;
    int j = 1;
    i = 42;

This should be folded into

    var i = 20;
    val j = 1;
    i = 42;

Do you get this result?

Anyways, this means that I could do the following and everything will compile the same

    int i = 20;
    final int j = 1;
    i = 42;

**Comment by anaumidis** [comment]
Oh! I get it now... :smile:
You also fold to `val` the effectively final variables... That's even better!
Thank you for the clarification.

**Comment by SUPERCILEX** [comment]
@cheptsov I believe this issue can be closed now.

**Comment by ciscorucinski** [comment]
@anaumidis you can close this issue, too.
