### ISSUE TITLE
Plugin should be disabled when editing Kotlin

### ISSUE THREAD

**Issue by SUPERCILEX** [cheptsov/AdvancedExpressionFolding#68]
It's got these annoying bugs where it pointlessly shrinks Kotlin code that shouldn't be shrunken:
![image](https://cloud.githubusercontent.com/assets/9490724/26814199/77756da8-4a38-11e7-8ad6-c33f136fe321.png)

This is the original which is much better:
![image](https://cloud.githubusercontent.com/assets/9490724/26814169/4d3693fa-4a38-11e7-8faa-147c168a6a58.png)

Plugin version: 0.9.2

**Comment by cheptsov** [comment]
Are you sure this is caused by this plugin? This plugin works only for Java code. Can you double check it, e.g. uninstall  the plugin and see if it helps or not.

**Comment by SUPERCILEX** [comment]
@cheptsov Hmmm, ok so it's not your fault. Even with the plugin disabled, it still happens. Who am I supposed to blame? 😄

https://youtrack.jetbrains.com/issue/IDEA-174346
