### ISSUE TITLE
Wrong folding when merge strings

### ISSUE THREAD

**Issue by mtrakal** [cheptsov/AdvancedExpressionFolding#70]
`Version: 0.9.1`

I have `mMenuItemSettings.setTitle(getString(R.string.manage_account) + " - " + account.getName());`
![clipboard02](https://user-images.githubusercontent.com/1458891/26923011-29fbbfb8-4c41-11e7-82e9-fe5e97fe35dd.png)

**Comment by cheptsov** [comment]
Should work now ith 0.9.9.4
