### ISSUE TITLE
stringVar[0] folded to stringVar.first()

### ISSUE THREAD

**Issue by petteyg** [cheptsov/AdvancedExpressionFolding#72]
It's not really a great fold if the resulting text is longer than the original code :)

**Comment by ciscorucinski** [comment]
As a standalone example, it would seem to be a bad fold; however, shorter
does not always mean better. In this case, the ever so slightly longer
folded text provided a very good description of what you wanted to get....
You wanted the first item in the array.

Plus, this fold is paired with last() and last is much shorter than
.getSize() - 1 or .length - 1.

**Comment by petteyg** [comment]
String[] ss = StringUtils.split("I will. always have. three dots. in here", '.');
String ss0 = ss[0];
String ss1 = ss[1];
String ss2 = ss[2];

There is no "last()" fold if I'm not using getSize() -1, and to be blunt, if you can't tell that element 0 is the "first" element, you have no business coding.

**Comment by cheptsov** [comment]
Sometimes I have similar feelings. Do you think it makes sense to remove the ".first()" folding but keep ".last()"?

**Comment by petteyg** [comment]
last() is always shorter and more concise in its meaning, so as a "fold" it makes plenty of sense.

**Comment by ciscorucinski** [comment]
I think the first fold is useful. Personally, you should expand it to other indexes.

The human mind is use to positional notation; only in computers do you use an unintuitive zero-based cardinality. That is why languages have implemented the first notation for indexes. 

In the given example above, it is way more intuitive to write


~~~
int a = ss.first();
int b = ss.second();
int c = ss.third();
~~~

Or something more precise...

~~~
int a = ss.1st();
int b = ss.2nd();
int c = ss.3rd();
~~~

Or even...


~~~
int a = ss.1st;
int b = ss.2nd;
int c = ss.3rd;
~~~

This would be a huge lose if you got rid of `first` or didn't make it more concise as indicated above.

**Comment by petteyg** [comment]
Again, a programmer worth spit knows counts from 0 naturally.

**Comment by cheptsov** [comment]
I dropped .first and kept .last
