### ISSUE TITLE
Missing closing curly brace in setter with concatenated string value

### ISSUE THREAD

**Issue by overmind1001** [cheptsov/AdvancedExpressionFolding#76]
![adv_fold_plugin_bug](https://user-images.githubusercontent.com/2333862/27726189-cf7b5a68-5d92-11e7-8932-f817d6a0cbfb.png)

Plugin verision: 0.9.4

**Comment by cheptsov** [comment]
Should be fixed with 0.9.6 (EAP), please check!

**Comment by overmind1001** [comment]
It's fixed!
