### ISSUE TITLE
Visually hide "unnecessary" curly braces

### ISSUE THREAD

**Issue by lukaseder** [cheptsov/AdvancedExpressionFolding#80]
I personally don't like curly braces where they're not syntactically needed, e.g.:

```java
// Aaaaaagh, eye cancer:
if (something) {
  doX();
}
else {
  doY();
}

// Oooh, the pain has gone:
if (something)
  doX();
else
  doY();
```

Now, instead of starting fights with [whoever controls the style guide](http://i.imgur.com/B3sdXWA.png), I'd love to just not *see* the curly braces if they're unnecessary.

Would that be an interesting addition to your plugin?

**Comment by cheptsov** [comment]
I like the idea. Do I correctly understand that we are only talking about control flow statements, such as if, try, switch, what else?

**Comment by lukaseder** [comment]
Well, there are several levels of course:

1. Apply this only to those curly braces where removing them would still be syntactically correct. This essentially only includes "blocks": https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-Block (as e.g. standalone blocks, if-else/while/do/for statements with block bodies). 
2. Apply this to control flow constructs where the curly braces are part of the language (e.g. try-catch-finally, switch). This would produce incorrect syntax in Java.
3. Apply this also to other constructs and pretend Java is Python or something (e.g. class bodies, method bodies, etc.)

I was mostly thinking about 1, but if there are several options, perhaps 2 and 3 are possible too.

**Comment by cheptsov** [comment]
Will be available in the Stable channel within a couple of weeks. Available in the EAP channel now.
