### ISSUE TITLE
Hide semicolons 😂

### ISSUE THREAD

**Issue by cheptsov** [cheptsov/AdvancedExpressionFolding#83]

**Comment by ciscorucinski** [comment]
While it might be nice....Not to certain if it would help or hinder developers. 

I think zero-artifact folds should be used very minimally. I think you agree because of this emoji haha

**Comment by cheptsov** [comment]
Yes, I simply want to do it as a pre experiment just to see how painful it is to use this feature.

**Comment by ciscorucinski** [comment]
I suppose if you are missing a semicolon, then you will only notice it at compile time. If that's the case, then stacktrace will let you know where the issue is. So impact shouldn't be too bad.

**Comment by cheptsov** [comment]
Available in the last EAP build, disabled by default
