### ISSUE TITLE
Fold null checked Ternary into Elvis ?: operators

### ISSUE THREAD

**Issue by nathanmbrown** [cheptsov/AdvancedExpressionFolding#9]
e.g.
`ternaryOutput = (sampleText != null) ? sampleText : 'Viva Las Vegas!';`
becomes
`elvisOutput = sampleText?: 'Viva Las Vegas!';`

**Comment by cheptsov** [comment]
Nice idea, will give it a try!

**Comment by stokito** [comment]
hah, I just wanted to propose the same :-)
Also I would like to ask you to handle another case:
```java
ternaryOutput = (sampleText == null) ? 'Viva Las Vegas!' : sampleText;
```

**Comment by cheptsov** [comment]
Plus a request from @artspb: `node != null ? node.getPsi() : null` -> `node?.getPsi()`? :

**Comment by nathanmbrown** [comment]
I'd already suggested this in https://github.com/cheptsov/AdvancedExpressionFolding/issues/10, omitted the trailing ? though, will fix that.

**Comment by cheptsov** [comment]
https://twitter.com/andrey_cheptsov/status/834779360179675136
