### ISSUE TITLE
Incorrect string builder folding 

### ISSUE THREAD

**Issue by aristotll** [cheptsov/AdvancedExpressionFolding#91]
```js
int curYear = calendar.get(1);
String date = (new StringBuilder()).append(curYear).append("01").toString();
```
The result: <img width="402" alt="2017-10-13 16 36 31" src="https://user-images.githubusercontent.com/13341544/31537449-d0213154-afc7-11e7-8c17-8fdd15c69b1b.png">

Two problems:
1. curYear does not change.
2. toString is redundant.

Thanks.

**Comment by jfcabral** [comment]
Hello
I've tested this issue in v0.9.9.3 and:
1. ❌ **+=** operator still appears instead of **+**
2.  :white_check_mark: redundant **toString** seems to be fixed 👍

**Comment by cheptsov** [comment]
Thanks for reporting and the pull requests. Should work now with 0.9.9.4.
