### ISSUE TITLE
Incorrect assert folding

### ISSUE THREAD

**Issue by jfcabral** [cheptsov/AdvancedExpressionFolding#95]
Hello, I've just realized this odd folding behavior
```java
        if (parameter == null) {
            throw new ArgumentNullException(parameterName);
        }
```
is getting folded into
```java
        assert parameter != null;
        }
```
Specs:
* Advanced Java Folding v0.9.9.1
* IntelliJ IDEA 2017.2.5
* Build #IC-172.4343.14, built on September 26, 2017
* JRE: 1.8.0_152-release-915-b12 amd64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Windows 10 10.0

**Comment by cheptsov** [comment]
Should work with 0.9.9.4

**Comment by jfcabral** [comment]
Thank you @cheptsov it works like a charm 😄
