### ISSUE TITLE
incorrect folding with map casting

### ISSUE THREAD

**Issue by aristotll** [cheptsov/AdvancedExpressionFolding#96]
```java
final Object tableName = ((Map<String, ?>) first).get(".table");
```

<img width="360" alt="2017-11-11 10 03 30" src="https://user-images.githubusercontent.com/13341544/32685205-9bc36dfc-c6c7-11e7-99df-66cc85514fba.png">

there is a redundant right bracket .

**Comment by jfcabral** [comment]
Agreed :) It seems to be the same issue as https://github.com/cheptsov/AdvancedExpressionFolding/issues/71 though...
