### ISSUE TITLE
The omitted bracket in if can cause problem.

### ISSUE THREAD

**Issue by aristotll** [cheptsov/AdvancedExpressionFolding#97]
Code:
```java
        if(true) { //Note:  if and ( have no space in  between.
            log.info("true");

        }
```
Visaul result:
<img width="280" alt="2017-11-13 14 53 02" src="https://user-images.githubusercontent.com/13341544/32713029-60ddec82-c882-11e7-984b-2d77a93fb1a9.png">

**Comment by cheptsov** [comment]
Thanks for reporting. Will fix shortly.
